name: Action on Pull Request
run-name: ${{ github.actor }} triggered action by a pull request

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  id-token: read
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read|write


jobs:
  # Job 1
  build-run-lorenz_96:
    # Runner instance OS
    runs-on: ubuntu-latest
    # Deploy container on top of runner instance
    container: 
      image: achaup/dart_dep:root
      options: "--cap-add=SYS_PTRACE"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set checked out repo as a safe git directory
        run: git config --global --add safe.directory ${{ github.workspace }}
      - name: Build and run lorenz_96
        uses: ./.github/actions/build_run_model 
        with: 
          model: lorenz_96
          run-program: ./filter
          use-mpi: true
          mpi-n-tasks: 2
  
  # Job 2
  build-run-lorenz_63:
    runs-on: ubuntu-latest
    container:
      image: achaup/dart_dep:root
      options: '--cap-add=SYS_PTRACE'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set checked out repo as a safe git directory
        run: git config --global --add safe.directory ${{ github.workspace }}
      - name: Build and run lorenz_63 with no mpi
        uses: ./.github/actions/build_run_model
        with:
          model: lorenz_63
          run-program: ./filter
          use-mpi: false
