name: Build DART from container
run-name: ${{ github.actor }} building & compiling from pull request
on:
  pull_request:
    types: [opened, reopened]
jobs:
  build-run-lorenz_96:
    # Runner instance OS
    runs-on: ubuntu-latest
    container: 
      # Pull Docker image from Dockerhub
      image: achaup/dart_dep:root
      # Docker run argument added to solve MPI issues in containers
      options: "--cap-add=SYS_PTRACE"
    steps:
      # For each new set of steps, workdir is changed to
      # the root directory of checked out repo (in this case: ~/github-actions-test/github-actions-test)
      - name: Checkout repo
        uses: actions/checkout@v3
        # Declare safe directory to avoid dubious ownership of checked out repo in container
        run: git config --global --add safe.directory /__w/github-actions-test/github-actions-test
      - name: Creating mkmf build template
        run: |
          cd build_templates
          cp mkmf.template.gfortran mkmf.template
          echo "NETCDF = /usr/" >> mkmf.template
      - name: Building lorenz_96 model
        run: |
          cd models/lorenz_96/work/
          ./quickbuild.sh
      - name: Running lorenz_96 with MPI
        # max n=2 as standard github runners only have 2 physical cores
        run: |
          cd models/lorenz_96/work/
          mpirun -n 2 --allow-run-as-root ./filter
