name: Automatically Build & Compile from Pull Request
run-name: ${{ github.actor }} building & compiling from pull request
on:
  pull_request:
    types: [opened, reopened]
jobs:
  Build-Compile-DART:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: Updating runner's packages
        run: sudo apt-get update
      - name: Installing libnetcdf-dev
        run: sudo apt-get install libnetcdf-dev
      - name: Installing libnetcdff-dev
        run: sudo apt-get install libnetcdff-dev
      - name: Installing netcdf-bin
        run: sudo apt-get install netcdf-bin
      - name: Installing libopenmpi-dev
        run: sudo apt-get install libopenmpi-dev
      - name: Installing gfortran
        run: sudo apt-get install gfortran
      - name: Creating build template
        run: |
          ls -l
          cd build_templates
          pwd
          ls -l
          cp mkmf.template.gfortran mkmf.template
          ls -l
          echo "NETCDF=/usr/" >> mkmf.template
          ls /usr/
          ls /usr/bin/
      - name: Building lorenz_96 model
        run: |
          pwd
          cd models/lorenz_96/work/
          ls -l
          ./quickbuild.sh
