name: 'Build and run model'
description: 'Build and run given model'
inputs:
  model:  # name of model to build & run
    description: 'name of existing DART model'
    required: true
    default: 'lorenz_96'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo Building ${{ inputs.model }}.
      shell: bash
    # - id: random-number-generator
    #   run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
    #   shell: bash
    - run: |
        pwd
        ls -l
      shell: bash 
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    # - run: goodbye.sh
    #   shell: bash
