name: 'Build and run model'
description: 'Build and run given model'

inputs:
  model:  # name of model to build & run
    description: 'name of existing DART model'
    required: true
    default: 'lorenz_96'
  run-program:  # program to run after compilation
    description: 'name of program to run in model/work directory after compile'
    required: true
    default: './filter'
  run-program-args:
    type: string
    description: 'arguments to use when running specified program'
    required: false
    default: ''
  use-mpi:
    description: 'specify whether to run program with MPI or not'
    type: boolean
    required: true
    default: true
  mpi-n-tasks:
    description: 'specify number of mpi tasks to run with program if mpi is used'
    type: number
    required: false
    default: 2

# research conditionals

outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Creating Makefile template
      run: |
        cd build_templates
        cp mkmf.template.gfortran mkmf.template
        echo "NETCDF = /usr/" >> mkmf.template
      shell: bash

    - name: Building ${{ inputs.model }} model
      run: |
        cd models/${{ inputs.model }}/work
        ./quickbuild.sh
      shell: bash

    - name: Running ${{ inputs.model }} ${{ inputs.run-program }} program
      if: ${{ inputs.use-mpi }} 
      run: |
        cd models/${{ inputs.model }}/work/
        mpirun -n ${{ inputs.mpi-n-tasks }} --allow-run-as-root ${{ inputs.run-program }} ${{ inputs.run-program-args }}
      shell: bash
    - name: Running ${{ inputs.model }} ${{ inputs.run-program }} program
      if: ${{ !inputs.use-mpi }}
      run: |
        cd models/${{ inputs.model }}/work/
        ${{ inputs.run-program }} ${{ inputs.run-program-args }}
      shell: bash
